### ISSUE TITLE
Serial Init

### ISSUE THREAD

**Issue by sop64** [Industruino/Indio#6]
This example does not print channel data to Arduino IDE serial monitor windows unless I change the serial port initialization command from  SerialUSB.begin(9600) to Serial.begin(9600) (Arduino standard); 

Than it prints regularly with SerialUSB.print.

Thanks Paolo

**Comment by tomtobback** [comment]
Hi Paolo, apologies for that, you are correct that the example was not working: the problem was with the line ```while (!Serial) {}``` which makes the code wait there until a connection to ```Serial``` is established (D0/D1). This should be changed to ```SerialUSB``` - i have updated the code.
