### ISSUE TITLE
analogReadMode hangs

### ISSUE THREAD

**Issue by albydnc** [Industruino/Indio#8]
I've used the AnalogIn example in the Indio library and it can't get past analogReadMode
Using arduino 1.8.8 on Ubuntu 18.04.2

**Comment by tomtobback** [comment]
hi, are you powering the INDIO unit with external 12/24V? this is necessary for the baseboard functions
also, the code is waiting for a SerialUSB connection, so you will have to open the Arduino IDE's Serial Monitor to proceed beyond line 24. if you don't want to use the Serial Monitor, comment out these lines 24-27
